pool: terraform_agent
trigger: none
jobs:
 - job: Terraform_Initialization_Planing
   displayName: Terraform_Init
   steps:
   - task: TerraformTask@5
     displayName: Intilization_Terraform
     inputs:
       provider: 'azurerm'
       command: 'init'
       workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
       commandOptions: '-reconfigure -upgrade'
       backendServiceArm: 'Adv_Terraform_Pipeline'
       backendAzureRmResourceGroupName: 'shubham-terraform1'
       backendAzureRmStorageAccountName: 'terraformstg970777'
       backendAzureRmContainerName: 'containerterraform'
       backendAzureRmKey: 'terraform.tfstate'
   
   - task: TerraformTask@5
     displayName: Planing_Azure_Resources
     inputs:
       provider: 'azurerm'
       command: 'plan'
       workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
       environmentServiceNameAzureRM: 'Adv_Terraform_Pipeline'

 - job: Manual_validation
   displayName: Validation
   dependsOn: Terraform_Initialization_Planing
   pool: server

   steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440
      inputs:
        notifyUsers: 'abc@xyz.123'
        instructions: 'Please approve this Terraform plan request'
          

 - job: Terraform_Applying
   dependsOn: Manual_validation
   displayName: Terraform_Re-Initialization
   steps:
   - task: TerraformTask@5
     displayName: Intilization_Terraform
     inputs:
       provider: 'azurerm'
       command: 'init'
       workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
       commandOptions: '-upgrade'
       backendServiceArm: 'Adv_Terraform_Pipeline'
       backendAzureRmResourceGroupName: 'shubham-terraform1'
       backendAzureRmStorageAccountName: 'terraformstg970777'
       backendAzureRmContainerName: 'containerterraform'
       backendAzureRmKey: 'terraform.tfstate'
    
   - task: TerraformTask@5
     displayName: AzureResource_Creations
     inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'Adv_Terraform_Pipeline'